-- Run this in Supabase SQL Editor.
-- Full schema for driver/guardian linking + drowsiness tracking.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text not null,
  role text not null check (role in ('driver', 'guardian')),
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_email_unique_idx
  on public.profiles (lower(email));

create table if not exists public.driver_guardians (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint driver_guardians_not_self check (driver_id <> guardian_id),
  constraint driver_guardians_unique_pair unique (driver_id, guardian_id)
);

create index if not exists driver_guardians_driver_idx
  on public.driver_guardians (driver_id, created_at desc);

create index if not exists driver_guardians_guardian_idx
  on public.driver_guardians (guardian_id, created_at desc);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.profiles(id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  status text not null default 'ACTIVE'
);

create index if not exists sessions_driver_idx
  on public.sessions (driver_id, started_at desc);

create table if not exists public.drowsiness_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(id) on delete set null,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  ear_value double precision,
  duration_seconds double precision,
  severity text not null check (severity in ('LOW', 'MEDIUM', 'HIGH')),
  created_at timestamptz not null default now()
);

create index if not exists drowsiness_events_driver_idx
  on public.drowsiness_events (driver_id, created_at desc);

create index if not exists drowsiness_events_session_idx
  on public.drowsiness_events (session_id, created_at desc);

create table if not exists public.guardian_notifications (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid references public.sessions(id) on delete set null,
  message text not null,
  severity text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists guardian_notifications_guardian_idx
  on public.guardian_notifications (guardian_id, is_read, created_at desc);

create index if not exists guardian_notifications_driver_idx
  on public.guardian_notifications (driver_id, created_at desc);

-- Backward compatibility with the existing backend routes that still write to driving_sessions.
create table if not exists public.driving_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  event_type text not null default 'DROWSINESS_DETECTED',
  ear_value double precision,
  duration_seconds double precision,
  severity text not null check (severity in ('LOW', 'MEDIUM', 'HIGH')),
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists driving_sessions_user_created_idx
  on public.driving_sessions (user_id, created_at desc);

create index if not exists driving_sessions_session_idx
  on public.driving_sessions (session_id);

create or replace function public.sync_profile_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_role text;
begin
  profile_role := lower(coalesce(new.raw_user_meta_data ->> 'role', ''));
  if profile_role not in ('driver', 'guardian') then
    profile_role := null;
  end if;

  if profile_role is not null then
    insert into public.profiles (id, name, email, role)
    values (
      new.id,
      coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
      lower(new.email),
      profile_role
    )
    on conflict (id) do update
      set email = excluded.email,
          name = coalesce(excluded.name, public.profiles.name),
          role = coalesce(excluded.role, public.profiles.role);
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_sync_profile on auth.users;
create trigger on_auth_user_created_sync_profile
after insert on auth.users
for each row execute function public.sync_profile_from_auth();
